src/components/atoms/Input/Input.tsx, src/components/atoms/Option/Option.tsx, src/components/organisms/RegisterForm/RegisterForm.md, src/components/organisms/RegisterForm/RegisterForm.tsx, tsconfig.json, webpack.config.js
=> Register Form LMSDEMO-48

src/components/atoms/Link/Link.tsx, src/components/atoms/NoteAction/NoteAction.md, src/components/atoms/NoteAction/NoteAction.tsx
=> note with action

src/components/molecules/Orders/Orders.tsx
=> feature/LMSDEMO-155 - styles for orders with flex

src/components/players/AudioVideoPlayer/AudioVideoPlayer.md, src/components/players/AudioVideoPlayer/AudioVideoPlayer.tsx
added missing background after clicking play
=> LMSDEMO-115 AudioPlayer

src/components/molecules/CourseCard/CourseCard.md, src/components/molecules/CourseCard/CourseCard.tsx
@mtmotyka check if any other card should have the same approach
=> LMSDEMO-208 - CourseCard Title bug

src/components/organisms/ResponsiveImage/ResponsiveImage.tsx, src/components/players/ImagePlayer/ImagePlayer.tsx
maybe the problem is here, I am not 100% sure, after merge I will check again
=> LMSDEMO-529 - Agenda img bug

src/components/players/PdfPlayer/PdfPlayer.tsx
https://escl24.atlassian.net/browse/LMSDEMO-599
=> Add config props to <PdfPlayer>

src/components/organisms/CourseAgenda/CourseAgenda.tsx, src/components/organisms/CourseAgenda/mock.json, src/components/organisms/CourseProgram/mock.json
Close this issue https://github.com/EscolaLMS/Components/issues/248
=> Fix nested-interactive AXE a11y errors

src/components/players/H5Player/H5Player.md, src/components/players/H5Player/H5Player.tsx
https://escl24.atlassian.net/browse/LMSDEMO-617
=> Exclude h5p-icons from css font rules and add 2 examples to markdown

src/components/organisms/MyProfileForm/MyProfileForm.tsx
https://escl24.atlassian.net/browse/LMSDEMO-602
=> Lmsdemo 602

package.json, src/components/molecules/MarkdownRenderer/MarkdownRenderer.tsx, src/components/organisms/TasksComponent/index.tsx, src/components/players/ImagePlayer/ImagePlayer.tsx, src/utils/utils.ts
This had to be done, due to `react-image-lightbox` not supporting react 18.
=> feature: lightbox lib changes

package.json
Add missing packages to package.json
=> Fix missing packages

package.json, src/components/molecules/MarkdownRenderer/MarkdownRenderer.tsx, src/components/organisms/ResponsiveImage/ResponsiveImage.tsx, src/components/players/ImagePlayer/ImagePlayer.tsx, src/utils/utils.ts
This MR waits for sdk release with [these](https://github.com/EscolaLMS/sdk/pull/263) changes.
=> bugfix: lightbox lib change

src/components/molecules/MarkdownRenderer/MarkdownRenderer.md, src/components/molecules/MarkdownRenderer/MarkdownRenderer.tsx, src/utils/components/markdown/index.ts
[WC-924]
Fix <mark> tag rendering.
Add default styles for MarkdownRenderer same as in admin panel.
Add new examples for MarkdownRenderer.
https://escl24.atlassian.net/browse/WC-924
[WC-924]: https://escl24.atlassian.net/browse/WC-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WC-924] Add default styles, new examples and fix html mark tag for MarkdownRenderer

src/components/molecules/Tags/Tags.md, src/components/molecules/Tags/Tags.tsx, src/components/molecules/Tags/mock.json, src/styleguide/i18n.ts
Add Tags select component to molecules.
=> Add Tags select component to molecules.

src/components/organisms/CourseAgenda/_components/CourseAgendaTopic.tsx
Fix bug with next lesson button in one before last topic.
https://escl24.atlassian.net/browse/WELLMS-352
=> [WELLMS-352] Fix bug with next lesson button in one before last topic.

src/components/molecules/CourseTopNav/CourseTopNav.tsx, src/components/organisms/CourseAgenda/_components/CourseAgendaLesson/index.tsx, src/components/organisms/CourseAgenda/_components/context.tsx, src/utils/course.ts
Fix bug with sequence of nested lessons and topics in CourseAgenda.
Fix TS error with BookmarkableType in CourseTopNav.
https://escl24.atlassian.net/browse/WELLMS-244
=> Fix bug with sequence of nested lessons and topics in CourseAgenda.

src/components/players/H5Player/H5Player.md, src/components/players/H5Player/H5Player.tsx
Add hideActionButtons prop to H5Player to hide actions buttons of h5p.
https://escl24.atlassian.net/browse/WELLMS-251
=> Add hideActionButtons prop to H5Player to hide actions buttons of h5p.

src/components/players/PdfPlayer/PdfPlayer.tsx
Fixed a bug with the onTopicEnd function which was executed only after double-clicking on the last page. Now it is executed when entering the last page of the PDF.
Fixed a bug with the next button disabled when returning from the last page to the previous one.
=> [WELLMS-400] Fix pdf onTopicEnd function.

.github/workflows/a11y.yml, .github/workflows/publish.yml, .github/workflows/tests.yaml
update-node.js in actions form 16 to 20
=> update-node.js in actions form 16 to 20

src/components/atoms/ProgressBar/ProgressBar.tsx, src/components/molecules/CourseTopNav/CourseTopNav.tsx, src/components/organisms/CourseAgenda/_components/CourseAgendaTopic.tsx
Add allButtonsDisabled prop for CourseTopNav.
Add variants for ProgressBar.
=> Add autoscroll to nerest topic element.

package.json
=> Update h5p player package.

src/components/molecules/CourseTopNav/CourseTopNav.tsx
Show finish button on last page even if course finished for congrats page.
=> Show finish button on last page

src/components/atoms/Modal/Modal.tsx, src/theme/provider.tsx, src/theme/red.ts
=> Fix modal styles.
